/**
 * 风格预设库 —— 155 个风格(v12.273 由 64 扩容) (初版 60, anime 类后补「美漫 / 原神崩坏 / 雾山水墨 / 海棠唯美」四款)
 *
 * 分类：realistic 31 / anime 36 / artistic 27 / retro 30 / experimental 31(v12.273 扩容后)。
 *
 * 缩略图统一由 MJ API 通过 `scripts/generate-style-thumbnails.ts` 生成，
 * 输出到 `public/styles/<id>.jpg`。
 *
 * promptFragment 将在生成图/视频时注入到 prompt 末尾（逗号分隔），
 * 由 orchestrator 在调用具体 engine service 前统一拼接。
 */

import type { StylePreset } from '@/types/agents';

export const STYLE_PRESETS: StylePreset[] = [
  // ========== REALISTIC 写实 (12) ==========
  {
    id: 'cinematic',
    name: '电影感',
    nameEn: 'Cinematic',
    category: 'realistic',
    thumbnail: '/styles/cinematic.jpg',
    promptFragment: 'cinematic lighting, shallow depth of field, film grain, anamorphic lens, color graded, 35mm',
    negativePrompt: 'cartoon, anime, flat lighting',
    recommendedEngine: 'seedance2',
    popularity: 98,
  },
  {
    id: 'documentary',
    name: '纪录片',
    nameEn: 'Documentary',
    category: 'realistic',
    thumbnail: '/styles/documentary.jpg',
    promptFragment: 'documentary photography, handheld camera, natural light, candid moment, realistic tones',
    recommendedEngine: 'kling3',
    popularity: 72,
  },
  {
    id: 'photojournalism',
    name: '新闻摄影',
    nameEn: 'Photojournalism',
    category: 'realistic',
    thumbnail: '/styles/photojournalism.jpg',
    promptFragment: 'photojournalistic, gritty realism, high contrast, black and white tones, 50mm lens',
    popularity: 58,
  },
  {
    id: 'portrait-natural',
    name: '自然光人像',
    nameEn: 'Natural Light Portrait',
    category: 'realistic',
    thumbnail: '/styles/portrait-natural.jpg',
    promptFragment: 'natural window light portrait, soft shadows, creamy bokeh, 85mm, skin texture detail',
    recommendedEngine: 'kling3',
    popularity: 88,
  },
  {
    id: 'adventure',
    name: '冒险',
    nameEn: 'Adventure',
    category: 'realistic',
    thumbnail: '/styles/adventure.jpg',
    promptFragment: 'epic adventure scene, lush untamed wilderness, dramatic volumetric god rays, sense of discovery and wonder, sweeping cinematic vista, rich saturated color',
    recommendedEngine: 'seedance2',
    popularity: 66,
  },
  {
    id: 'cave-moody',
    name: '洞穴暗调',
    nameEn: 'Moody Cave',
    category: 'realistic',
    thumbnail: '/styles/cave-moody.jpg',
    promptFragment: 'moody underground cavern, low-key chiaroscuro lighting, warm glowing accents against deep shadow, volumetric light shafts, mysterious subterranean atmosphere, cinematic darkness',
    recommendedEngine: 'kling3',
    popularity: 92,
  },
  {
    id: 'time-travel',
    name: '穿越',
    nameEn: 'Time Travel',
    category: 'realistic',
    thumbnail: '/styles/time-travel.jpg',
    promptFragment: 'time-travel portal, swirling luminous vortex, ethereal blue energy ring, figure stepping through dimensions, glowing particles, sci-fi fantasy wonder, cinematic atmosphere',
    recommendedEngine: 'seedance2',
    popularity: 64,
  },
  {
    id: 'fashion-editorial',
    name: '时尚大片',
    nameEn: 'Fashion Editorial',
    category: 'realistic',
    thumbnail: '/styles/fashion-editorial.jpg',
    promptFragment: 'high fashion editorial, Vogue cover, dramatic studio lighting, strong pose, matte finish',
    popularity: 75,
  },
  {
    id: 'street-photography',
    name: '街拍',
    nameEn: 'Street Photography',
    category: 'realistic',
    thumbnail: '/styles/street-photography.jpg',
    promptFragment: 'street photography, candid urban moment, Leica M6 film look, grainy, dynamic composition',
    popularity: 70,
  },
  {
    id: 'macro',
    name: '微距',
    nameEn: 'Macro',
    category: 'realistic',
    thumbnail: '/styles/macro.jpg',
    promptFragment: 'macro photography, extreme close up, razor sharp focus, intricate detail, shallow depth',
    popularity: 45,
  },
  {
    id: 'food-styled',
    name: '美食',
    nameEn: 'Food Styling',
    category: 'realistic',
    thumbnail: '/styles/food-styled.jpg',
    promptFragment: 'food photography, overhead 45 degree angle, soft diffused light, appetizing color, steam',
    popularity: 52,
  },
  {
    id: 'hyperrealism',
    name: '超写实',
    nameEn: 'Hyperrealism',
    category: 'realistic',
    thumbnail: '/styles/hyperrealism.jpg',
    promptFragment: 'hyperrealistic, 8k detail, perfectly rendered skin pores, every strand of hair visible, physically based',
    popularity: 80,
  },

  // ========== ANIME 动漫 (14) ==========
  {
    id: 'modern-anime',
    name: '日漫现代',
    nameEn: 'Modern Anime',
    category: 'anime',
    thumbnail: '/styles/modern-anime.jpg',
    promptFragment: 'modern anime style, vibrant color, clean linework, expressive eyes, soft cel shading, Kyoto Animation',
    recommendedEngine: 'seedance2',
    popularity: 97,
  },
  {
    id: 'ghibli',
    name: '吉卜力',
    nameEn: 'Ghibli',
    category: 'anime',
    thumbnail: '/styles/ghibli.jpg',
    promptFragment: 'Studio Ghibli style, hand-painted backgrounds, soft watercolor clouds, warm nostalgic palette, Miyazaki',
    recommendedEngine: 'kling3',
    popularity: 95,
  },
  {
    id: 'makoto-shinkai',
    name: '新海诚',
    nameEn: 'Makoto Shinkai',
    category: 'anime',
    thumbnail: '/styles/makoto-shinkai.jpg',
    promptFragment: 'Makoto Shinkai style, hyper detailed skies, volumetric god rays, wistful romantic atmosphere, vivid sunset',
    recommendedEngine: 'kling3',
    popularity: 94,
  },
  {
    id: 'kyoani',
    name: '京阿尼',
    nameEn: 'Kyoto Animation',
    category: 'anime',
    thumbnail: '/styles/kyoani.jpg',
    promptFragment: 'KyoAni style, crisp detailed character animation, soft pastel lighting, slice of life, melancholy warmth',
    popularity: 82,
  },
  {
    id: 'cel-shaded',
    name: '赛璐璐',
    nameEn: 'Cel Shaded',
    category: 'anime',
    thumbnail: '/styles/cel-shaded.jpg',
    promptFragment: 'classic cel shaded anime, flat color blocks, visible line art, retro 90s anime aesthetic',
    popularity: 68,
  },
  {
    id: 'shounen',
    name: '少年热血',
    nameEn: 'Shounen Action',
    category: 'anime',
    thumbnail: '/styles/shounen.jpg',
    promptFragment: 'shounen anime, dynamic action pose, speed lines, intense expression, saturated color, energetic',
    popularity: 78,
  },
  {
    id: 'shoujo',
    name: '少女唯美',
    nameEn: 'Shoujo Romance',
    category: 'anime',
    thumbnail: '/styles/shoujo.jpg',
    promptFragment: 'shoujo anime, sparkling eyes, floral frames, pastel color, dreamy romantic atmosphere',
    popularity: 60,
  },
  {
    id: 'chibi',
    name: 'Q 版',
    nameEn: 'Chibi',
    category: 'anime',
    thumbnail: '/styles/chibi.jpg',
    promptFragment: 'chibi style, super deformed, big head small body, cute rounded shapes, playful',
    popularity: 56,
  },
  {
    id: 'mecha',
    name: '机甲',
    nameEn: 'Mecha',
    category: 'anime',
    thumbnail: '/styles/mecha.jpg',
    promptFragment: 'mecha anime, detailed robot, panel lines, industrial, Gundam style, cinematic scale',
    popularity: 63,
  },
  {
    id: 'seinen-dark',
    name: '青年暗黑',
    nameEn: 'Dark Seinen',
    category: 'anime',
    thumbnail: '/styles/seinen-dark.jpg',
    promptFragment: 'dark seinen anime, mature tone, desaturated palette, heavy shadows, gritty realism, Berserk inspired',
    popularity: 71,
  },
  {
    id: 'chinese-animation',
    name: '国风动画',
    nameEn: 'Chinese Animation',
    category: 'anime',
    thumbnail: '/styles/chinese-animation.jpg',
    promptFragment: 'Chinese animation style, wuxia aesthetic, flowing robes, ink wash backgrounds, elegant lineart',
    recommendedEngine: 'viduq3',
    popularity: 85,
  },
  {
    id: 'donghua',
    name: '现代国漫',
    nameEn: 'Modern Donghua',
    category: 'anime',
    thumbnail: '/styles/donghua.jpg',
    promptFragment: 'modern donghua 3D animation style, stylized cel look, vivid color, cinematic action, Nezha style',
    recommendedEngine: 'viduq3',
    popularity: 84,
  },
  {
    id: 'american-comic',
    name: '美漫',
    nameEn: 'American Comic',
    category: 'anime',
    thumbnail: '/styles/american-comic.jpg',
    promptFragment: 'American superhero comic book style, bold black ink outlines, dramatic cross-hatching, Ben-Day halftone dots, dynamic foreshortening, saturated primary colors, Marvel DC graphic novel aesthetic',
    recommendedEngine: 'seedance2',
    popularity: 86,
  },
  {
    id: 'mihoyo-game',
    name: '原神崩坏',
    nameEn: 'Game Anime (miHoYo)',
    category: 'anime',
    thumbnail: '/styles/mihoyo-game.jpg',
    promptFragment: 'anime game cinematic render, polished 3D cel shading, miHoYo Genshin Impact Honkai aesthetic, gacha fantasy character design, vibrant gradient rim lighting, glossy highlights, open world JRPG splash art',
    recommendedEngine: 'seedance2',
    popularity: 93,
  },
  {
    id: 'wushan-ink',
    name: '雾山水墨',
    nameEn: 'Ink-Wash Action',
    category: 'anime',
    thumbnail: '/styles/wushan-ink.jpg',
    promptFragment: 'Chinese ink-wash donghua, sumi-e brush strokes, dynamic wuxia martial action, splattered flying ink, bold negative space, monochrome with a single vivid accent color, Fog Hill of Five Elements aesthetic',
    recommendedEngine: 'viduq3',
    popularity: 87,
  },
  {
    id: 'haitang-ethereal',
    name: '海棠唯美',
    nameEn: 'Ethereal Donghua',
    category: 'anime',
    thumbnail: '/styles/haitang-ethereal.jpg',
    promptFragment: 'ethereal Chinese donghua, lush painterly backgrounds, warm tungsten lantern glow, Fujian tulou roundhouse architecture, flowing hanfu silk, dreamlike folklore atmosphere, soft bloom, Big Fish Begonia aesthetic',
    recommendedEngine: 'kling3',
    popularity: 86,
  },

  // ========== ARTISTIC 艺术 (12) ==========
  {
    id: 'ink-wash',
    name: '水墨',
    nameEn: 'Ink Wash',
    category: 'artistic',
    thumbnail: '/styles/ink-wash.jpg',
    promptFragment: 'traditional Chinese ink wash painting, sumi-e, flowing brush strokes, monochrome gradient, rice paper texture',
    recommendedEngine: 'viduq3',
    popularity: 86,
  },
  {
    id: 'oil-painting',
    name: '油画',
    nameEn: 'Oil Painting',
    category: 'artistic',
    thumbnail: '/styles/oil-painting.jpg',
    promptFragment: 'classical oil painting, visible brush strokes, rich impasto, Rembrandt lighting, museum quality',
    popularity: 77,
  },
  {
    id: 'watercolor',
    name: '水彩',
    nameEn: 'Watercolor',
    category: 'artistic',
    thumbnail: '/styles/watercolor.jpg',
    promptFragment: 'watercolor painting, soft wet on wet bleeds, translucent layers, paper texture, delicate',
    popularity: 74,
  },
  {
    id: 'pencil-sketch',
    name: '铅笔素描',
    nameEn: 'Pencil Sketch',
    category: 'artistic',
    thumbnail: '/styles/pencil-sketch.jpg',
    promptFragment: 'detailed pencil sketch, graphite on paper, cross hatching, tonal gradient, study drawing',
    popularity: 51,
  },
  {
    id: 'woodcut',
    name: '版画',
    nameEn: 'Woodcut Print',
    category: 'artistic',
    thumbnail: '/styles/woodcut.jpg',
    promptFragment: 'woodcut print style, bold black lines, high contrast, Hokusai inspired, textured paper',
    popularity: 48,
  },
  {
    id: 'pop-art',
    name: '波普',
    nameEn: 'Pop Art',
    category: 'artistic',
    thumbnail: '/styles/pop-art.jpg',
    promptFragment: 'pop art style, Roy Lichtenstein dots, bold primary colors, comic panel aesthetic, screen print',
    popularity: 62,
  },
  {
    id: 'art-nouveau',
    name: '新艺术',
    nameEn: 'Art Nouveau',
    category: 'artistic',
    thumbnail: '/styles/art-nouveau.jpg',
    promptFragment: 'art nouveau, Alphonse Mucha, flowing organic lines, floral ornament, muted gold palette',
    popularity: 57,
  },
  {
    id: 'impressionism',
    name: '印象派',
    nameEn: 'Impressionism',
    category: 'artistic',
    thumbnail: '/styles/impressionism.jpg',
    promptFragment: 'impressionist painting, Monet style, broken brush strokes, dappled sunlight, pastel harmony',
    popularity: 67,
  },
  {
    id: 'surrealism',
    name: '超现实',
    nameEn: 'Surrealism',
    category: 'artistic',
    thumbnail: '/styles/surrealism.jpg',
    promptFragment: 'surrealist painting, Salvador Dali style, dreamlike, impossible geometry, melting shapes',
    popularity: 65,
  },
  {
    id: 'concept-art',
    name: '概念美术',
    nameEn: 'Concept Art',
    category: 'artistic',
    thumbnail: '/styles/concept-art.jpg',
    promptFragment: 'professional concept art, ArtStation trending, dramatic composition, matte painting, epic scale',
    recommendedEngine: 'kling3',
    popularity: 89,
  },
  {
    id: 'storybook',
    name: '绘本',
    nameEn: 'Storybook',
    category: 'artistic',
    thumbnail: '/styles/storybook.jpg',
    promptFragment: 'children storybook illustration, gouache, whimsical, rounded shapes, warm cozy palette',
    popularity: 59,
  },
  {
    id: 'gothic',
    name: '哥特',
    nameEn: 'Gothic',
    category: 'artistic',
    thumbnail: '/styles/gothic.jpg',
    promptFragment: 'gothic art, dark romanticism, cathedral architecture, candlelight, oil on canvas, Caravaggio inspired',
    popularity: 55,
  },

  // ========== RETRO 复古 (12) ==========
  {
    id: 'vhs-80s',
    name: '80s VHS',
    nameEn: '80s VHS',
    category: 'retro',
    thumbnail: '/styles/vhs-80s.jpg',
    promptFragment: '80s VHS aesthetic, scan lines, chromatic aberration, muted colors, analog tape artifacts',
    popularity: 73,
  },
  {
    id: 'hk-90s',
    name: '90s 港片',
    nameEn: '90s Hong Kong Cinema',
    category: 'retro',
    thumbnail: '/styles/hk-90s.jpg',
    promptFragment: '90s Hong Kong cinema, Wong Kar-wai, neon reflection, rainy night, smoky bar, film grain',
    recommendedEngine: 'kling3',
    popularity: 81,
  },
  {
    id: 'film-grain',
    name: '胶片颗粒',
    nameEn: 'Film Grain',
    category: 'retro',
    thumbnail: '/styles/film-grain.jpg',
    promptFragment: 'analog film grain, Kodak Portra 400, warm tones, soft contrast, organic imperfection',
    recommendedEngine: 'seedance2',
    popularity: 87,
  },
  {
    id: 'black-white-classic',
    name: '黑白老电影',
    nameEn: 'Classic Black & White',
    category: 'retro',
    thumbnail: '/styles/black-white-classic.jpg',
    promptFragment: 'classic black and white film, 1950s Hollywood, high contrast, dramatic shadow, Orson Welles',
    popularity: 64,
  },
  {
    id: 'super-8',
    name: '超 8 胶片',
    nameEn: 'Super 8',
    category: 'retro',
    thumbnail: '/styles/super-8.jpg',
    promptFragment: 'Super 8 home movie look, warm washed out color, vignetting, dust and scratches, summer memories',
    popularity: 53,
  },
  {
    id: 'polaroid',
    name: '宝丽来',
    nameEn: 'Polaroid',
    category: 'retro',
    thumbnail: '/styles/polaroid.jpg',
    promptFragment: 'Polaroid instant photo, square crop, faded color, white border, soft vignette, nostalgia',
    popularity: 66,
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    nameEn: 'Art Deco',
    category: 'retro',
    thumbnail: '/styles/art-deco.jpg',
    promptFragment: 'Art Deco 1920s, geometric gold ornament, symmetric composition, Gatsby era luxury',
    popularity: 58,
  },
  {
    id: 'vintage-poster',
    name: '复古海报',
    nameEn: 'Vintage Poster',
    category: 'retro',
    thumbnail: '/styles/vintage-poster.jpg',
    promptFragment: 'vintage travel poster, limited color palette, stylized illustration, WPA style',
    popularity: 61,
  },
  {
    id: 'pulp-comic',
    name: '老漫画',
    nameEn: 'Pulp Comic',
    category: 'retro',
    thumbnail: '/styles/pulp-comic.jpg',
    promptFragment: 'pulp comic book style, halftone dots, bold ink lines, vintage newsprint, 1960s aesthetic',
    popularity: 54,
  },
  {
    id: 'disco-70s',
    name: '70s 迪斯科',
    nameEn: '70s Disco',
    category: 'retro',
    thumbnail: '/styles/disco-70s.jpg',
    promptFragment: '70s disco aesthetic, mirror ball, glittering lights, warm orange and brown palette, funk',
    popularity: 49,
  },
  {
    id: 'ukiyoe',
    name: '浮世绘',
    nameEn: 'Ukiyo-e',
    category: 'retro',
    thumbnail: '/styles/ukiyoe.jpg',
    promptFragment: 'Japanese ukiyo-e woodblock print, Hokusai, flat color areas, bold outlines, traditional pigments',
    popularity: 69,
  },
  {
    id: 'chinese-dynasty',
    name: '古风工笔',
    nameEn: 'Chinese Gongbi',
    category: 'retro',
    thumbnail: '/styles/chinese-dynasty.jpg',
    promptFragment: 'Chinese Tang dynasty gongbi painting, delicate brushwork, mineral pigments, silk scroll',
    recommendedEngine: 'viduq3',
    popularity: 79,
  },

  // ========== EXPERIMENTAL 实验 (12) ==========
  {
    id: 'cyberpunk',
    name: '赛博朋克',
    nameEn: 'Cyberpunk',
    category: 'experimental',
    thumbnail: '/styles/cyberpunk.jpg',
    promptFragment: 'cyberpunk, neon lights, rain soaked streets, holographic signs, Blade Runner 2049, dystopian',
    recommendedEngine: 'seedance2',
    popularity: 99,
  },
  {
    id: 'low-poly',
    name: '低多边形',
    nameEn: 'Low Poly',
    category: 'experimental',
    thumbnail: '/styles/low-poly.jpg',
    promptFragment: 'low poly 3D art, flat shaded triangles, minimalist geometry, pastel gradient',
    popularity: 46,
  },
  {
    id: 'pixel-art',
    name: '像素艺术',
    nameEn: 'Pixel Art',
    category: 'experimental',
    thumbnail: '/styles/pixel-art.jpg',
    promptFragment: '16-bit pixel art, limited palette, SNES aesthetic, crisp pixels, dithering',
    popularity: 72,
  },
  {
    id: 'glitch',
    name: '故障艺术',
    nameEn: 'Glitch Art',
    category: 'experimental',
    thumbnail: '/styles/glitch.jpg',
    promptFragment: 'glitch art, datamoshing, RGB split, corrupted pixels, digital decay, vaporwave',
    popularity: 60,
  },
  {
    id: 'psychedelic',
    name: '迷幻',
    nameEn: 'Psychedelic',
    category: 'experimental',
    thumbnail: '/styles/psychedelic.jpg',
    promptFragment: 'psychedelic, kaleidoscope patterns, neon rainbow, fractal, 60s trippy art',
    popularity: 52,
  },
  {
    id: 'vaporwave',
    name: '蒸汽波',
    nameEn: 'Vaporwave',
    category: 'experimental',
    thumbnail: '/styles/vaporwave.jpg',
    promptFragment: 'vaporwave aesthetic, pink and cyan gradient, roman statue, grid floor, 80s nostalgia',
    popularity: 68,
  },
  {
    id: 'synthwave',
    name: '合成波',
    nameEn: 'Synthwave',
    category: 'experimental',
    thumbnail: '/styles/synthwave.jpg',
    promptFragment: 'synthwave, retrofuturism, neon grid, chrome text, purple pink sunset, 80s sci-fi',
    recommendedEngine: 'seedance2',
    popularity: 76,
  },
  {
    id: 'biopunk',
    name: '生物朋克',
    nameEn: 'Biopunk',
    category: 'experimental',
    thumbnail: '/styles/biopunk.jpg',
    promptFragment: 'biopunk, organic machinery, bioluminescent, wet surfaces, alien body horror, Cronenberg',
    popularity: 47,
  },
  {
    id: 'steampunk',
    name: '蒸汽朋克',
    nameEn: 'Steampunk',
    category: 'experimental',
    thumbnail: '/styles/steampunk.jpg',
    promptFragment: 'steampunk, brass gears, Victorian era, steam powered machines, gaslight, airships',
    popularity: 70,
  },
  {
    id: 'solarpunk',
    name: '太阳朋克',
    nameEn: 'Solarpunk',
    category: 'experimental',
    thumbnail: '/styles/solarpunk.jpg',
    promptFragment: 'solarpunk utopia, lush greenery, clean architecture, solar panels, optimistic bright palette',
    popularity: 55,
  },
  {
    id: 'abstract',
    name: '抽象',
    nameEn: 'Abstract',
    category: 'experimental',
    thumbnail: '/styles/abstract.jpg',
    promptFragment: 'abstract art, non-representational, bold color fields, geometric composition, Kandinsky',
    popularity: 43,
  },
  {
    id: 'afrofuturism',
    name: '非洲未来主义',
    nameEn: 'Afrofuturism',
    category: 'experimental',
    thumbnail: '/styles/afrofuturism.jpg',
    promptFragment: 'afrofuturism, tribal patterns meets sci-fi, gold and indigo, cosmic imagery, Wakanda inspired',
    popularity: 50,
  },
  // ══════════ v12.273 扩容:+91 个(64 → 155) ══════════
  // 五分类并行创作 → 程序化三重去重(id/中文名/英文名),含与原 64 个**交叉比对**(又剔出 5 个撞车)
  // → 质量复核剔同质与空泛 promptFragment(2 个)。缩略图待 scripts/generate-style-thumbnails 补;
  // UI 缺图有渐变占位兜底(StylePicker onError),画廊不会裂。

  // ---------- REALISTIC (+19) ----------
  {
    id: 'golden-hour-rim',
    name: '黄金时刻逆光',
    nameEn: 'Golden Hour Rim Light',
    category: 'realistic',
    thumbnail: '/styles/golden-hour-rim.svg',
    promptFragment: 'magic hour backlight 3200K, orange-gold rim halo, lens flare blooms, 85mm f/1.4 portrait, lifestyle candid, warm bokeh highlight orbs',
    negativePrompt: 'flat light, overcast, cool color temperature',
    recommendedEngine: 'viduq3',
    popularity: 92,
  },
  {
    id: 'food-commercial',
    name: '美食商业摄影',
    nameEn: 'Commercial Food Photography',
    category: 'realistic',
    thumbnail: '/styles/food-commercial.svg',
    promptFragment: 'commercial food styling, 100mm macro, single-side diffused rim flash, shallow f/2.8 texture focus, elevated plating, crisp specular highlight, clean neutral background',
    negativePrompt: 'messy plating, flat overhead light, wide angle distortion',
    recommendedEngine: 'seedance2',
    popularity: 85,
  },
  {
    id: 'portra-skin',
    name: '柯达Portra肤色',
    nameEn: 'Kodak Portra Skin Tones',
    category: 'realistic',
    thumbnail: '/styles/portra-skin.svg',
    promptFragment: 'Kodak Portra 400 emulation, warm creamy skin rendering, gentle highlight rolloff, pastel shadow palette, 85mm f/1.8 prime, soft window-light bokeh',
    negativePrompt: 'harsh skin, cool color grade, oversaturated',
    recommendedEngine: 'seedance2',
    popularity: 82,
  },
  {
    id: 'family-window',
    name: '家庭温情日常',
    nameEn: 'Intimate Family Documentary',
    category: 'realistic',
    thumbnail: '/styles/family-window.svg',
    promptFragment: 'soft north window light, 35mm f/2 prime, quiet domestic moment, warm indoor available light, emotional authenticity, low contrast gentle shadow',
    recommendedEngine: 'viduq3',
    popularity: 80,
  },
  {
    id: 'kodachrome-70s',
    name: '柯达克罗姆70s',
    nameEn: 'Kodachrome 1970s',
    category: 'realistic',
    thumbnail: '/styles/kodachrome-70s.svg',
    promptFragment: 'shot on Kodachrome 64 film, warm amber mid-tones, faded cyan shadows, fine tight grain, 50mm f/2 prime, 1970s color science, slightly warm white balance',
    negativePrompt: 'digital clean, cool blue tones, modern color grading',
    recommendedEngine: 'seedance2',
    popularity: 75,
  },
  {
    id: 'street-candid',
    name: '街头抓拍色彩',
    nameEn: 'Street Candid Color',
    category: 'realistic',
    thumbnail: '/styles/street-candid.svg',
    promptFragment: '35mm rangefinder color, zone focus f/8 street level, candid human decisive moment, slight warm film grain, natural available light, spontaneous composition',
    recommendedEngine: 'viduq3',
    popularity: 72,
  },
  {
    id: 'sports-freeze',
    name: '体育冻结瞬间',
    nameEn: 'Sports Action Freeze',
    category: 'realistic',
    thumbnail: '/styles/sports-freeze.svg',
    promptFragment: '1/2000s shutter freeze peak action, 400mm f/2.8 telephoto compressed, panning motion blur background, burst tracking focus, athletic exertion moment',
    negativePrompt: 'motion blur subject, static pose, slow shutter',
    recommendedEngine: 'kling3',
    popularity: 70,
  },
  {
    id: 'velvia-landscape',
    name: '富士Velvia风光',
    nameEn: 'Fuji Velvia Landscape',
    category: 'realistic',
    thumbnail: '/styles/velvia-landscape.svg',
    promptFragment: 'Fujifilm Velvia 50 emulation, hyper-saturated green and cyan channel, vivid shadow contrast, 16mm ultra-wide, tripod sharp landscape, golden sidelight',
    negativePrompt: 'muted, desaturated, flat overcast light',
    recommendedEngine: 'seedance2',
    popularity: 68,
  },
  {
    id: 'drone-aerial',
    name: '无人机正俯瞰',
    nameEn: 'Drone Aerial Overhead',
    category: 'realistic',
    thumbnail: '/styles/drone-aerial.svg',
    promptFragment: 'drone bird\'s-eye 12mm wide, orthographic top-down perspective, 200m altitude geometric pattern, mid-day neutral light, subtle altitude haze, landscape abstraction',
    recommendedEngine: 'kling3',
    popularity: 65,
  },
  {
    id: 'wildlife-telephoto',
    name: '野生动物长焦',
    nameEn: 'Wildlife Super Telephoto',
    category: 'realistic',
    thumbnail: '/styles/wildlife-telephoto.svg',
    promptFragment: '600mm f/4 super telephoto, eye-level animal portrait, creamy compressed background bokeh, morning golden sidelight, tracking focus sharp eye detail',
    recommendedEngine: 'kling3',
    popularity: 62,
  },
  {
    id: 'polaroid-instant',
    name: '宝丽来即时感',
    nameEn: 'Polaroid Instant Film',
    category: 'realistic',
    thumbnail: '/styles/polaroid-instant.svg',
    promptFragment: 'Polaroid One-Step emulation, soft center halation, edge orange light leak, slight overexposure bloom, white border frame, faded warm color shift',
    recommendedEngine: 'seedance2',
    popularity: 60,
  },
  {
    id: 'wet-pavement-night',
    name: '雨夜湿街倒影',
    nameEn: 'Wet Street Night Reflection',
    category: 'realistic',
    thumbnail: '/styles/wet-pavement-night.svg',
    promptFragment: 'wet asphalt night, puddle color reflection, 35mm f/2, streetlight and neon bokeh, rain foreground drop bokeh, urban nocturne, available sodium vapor light',
    recommendedEngine: 'kling3',
    popularity: 58,
  },
  {
    id: 'tropical-vivid',
    name: '热带浓彩烈日',
    nameEn: 'Tropical Vivid Sunlight',
    category: 'realistic',
    thumbnail: '/styles/tropical-vivid.svg',
    promptFragment: 'equatorial harsh overhead noon sun, vivid cyan-teal ocean, saturated green tropical foliage, 24mm wide, hard shadow, primary saturated palette',
    recommendedEngine: 'kling3',
    popularity: 55,
  },
  {
    id: 'architecture-geometry',
    name: '建筑几何对称',
    nameEn: 'Architectural Geometric',
    category: 'realistic',
    thumbnail: '/styles/architecture-geometry.svg',
    promptFragment: '17mm tilt-shift rectilinear, architectural symmetry axis, natural sidelight shadow plane, modernist minimalism, clean sky, lens correction no distortion',
    recommendedEngine: 'seedance2',
    popularity: 52,
  },
  {
    id: 'underwater-caustic',
    name: '水下焦散光影',
    nameEn: 'Underwater Caustic Light',
    category: 'realistic',
    thumbnail: '/styles/underwater-caustic.svg',
    promptFragment: 'underwater wide-angle 10mm housing, natural caustic light rays, blue-green ocean ambient, refraction barrel distortion, 15m depth, particle float',
    recommendedEngine: 'kling3',
    popularity: 50,
  },
  {
    id: 'nordic-pale',
    name: '北欧冷灰漫射',
    nameEn: 'Nordic Pale Diffused',
    category: 'realistic',
    thumbnail: '/styles/nordic-pale.svg',
    promptFragment: 'Scandinavian overcast diffused light, desaturated cool blue-grey palette, shadowless flat illumination, Nordic winter pale, muted low contrast, 35mm f/5.6',
    recommendedEngine: 'seedance2',
    popularity: 48,
  },
  {
    id: 'conflict-zone',
    name: '战地手持纪实',
    nameEn: 'Conflict Zone Handheld',
    category: 'realistic',
    thumbnail: '/styles/conflict-zone.svg',
    promptFragment: 'handheld 1/30s micro-shake, pushed ISO 3200 heavy grain, 28mm close-wide angle, available war zone daylight, reportage urgency, raw unmanipulated',
    negativePrompt: 'clean stabilized, low ISO, cinematic grade',
    recommendedEngine: 'kling3',
    popularity: 45,
  },
  {
    id: 'industrial-grit',
    name: '工业锈迹质感',
    nameEn: 'Industrial Grit Texture',
    category: 'realistic',
    thumbnail: '/styles/industrial-grit.svg',
    promptFragment: 'factory interior practical light, sodium vapor and fluorescent mixed color, rust oxidized metal surface texture, 24mm wide, desaturated gritty tone, deep shadow',
    recommendedEngine: 'seedance2',
    popularity: 38,
  },
  {
    id: 'clinical-cold',
    name: '临床冷白无影',
    nameEn: 'Clinical Cold White',
    category: 'realistic',
    thumbnail: '/styles/clinical-cold.svg',
    promptFragment: 'fluorescent 5600K clinical white balance, sterile environment, shadowless even illumination, ultra-sharp f/8, antiseptic white and silver tone, medical setting',
    negativePrompt: 'warm light, dramatic shadow, low key',
    recommendedEngine: 'viduq3',
    popularity: 33,
  },

  // ---------- ANIME (+20) ----------
  {
    id: 'kyoani-softlight',
    name: '京阿尼软光',
    nameEn: 'KyoAni Soft Glow',
    category: 'anime',
    thumbnail: '/styles/kyoani-softlight.svg',
    promptFragment: 'KyoAni house style, subsurface skin glow, shimmer hair shading, ambient occlusion rim light, 5600K warm interior, soft bokeh f2.8, theatrical 16:9 letterbox',
    recommendedEngine: 'seedance2',
    popularity: 75,
  },
  {
    id: 'mappa-dark-action',
    name: '暗调格斗',
    nameEn: 'MAPPA Dark Action',
    category: 'anime',
    thumbnail: '/styles/mappa-dark-action.svg',
    promptFragment: 'MAPPA animation aesthetic, high-contrast ink contour, kinetic smear frames, desaturated mid-tones, crimson impact accent, dutch-angle handheld camera feel, JJK visual language',
    recommendedEngine: 'kling3',
    popularity: 82,
  },
  {
    id: 'webtoon-romance',
    name: '韩漫恋爱',
    nameEn: 'Webtoon Romance',
    category: 'anime',
    thumbnail: '/styles/webtoon-romance.svg',
    promptFragment: 'Korean manhwa full-color vertical scroll, clean fine-line inking, cel-shade pastel highlight, manhwa soft-chin proportions, skin bloom glow, modern urban romance backdrop',
    recommendedEngine: 'viduq3',
    popularity: 90,
  },
  {
    id: 'donghua-3d-toon',
    name: '国产三维',
    nameEn: 'Chinese 3D Donghua',
    category: 'anime',
    thumbnail: '/styles/donghua-3d-toon.svg',
    promptFragment: 'Chinese toon-shaded 3D donghua, Ne Zha 2019 render aesthetic, ink-edge outline shader, jade atmospheric depth haze, red-black dramatic contrast, rim-lit character silhouette',
    recommendedEngine: 'kling3',
    popularity: 70,
  },
  {
    id: 'shojo-sakura',
    name: '少女花漫',
    nameEn: 'Shojo Floral Manga',
    category: 'anime',
    thumbnail: '/styles/shojo-sakura.svg',
    promptFragment: 'shojo manga star-catch eyes, N-screentone overlay, floating cherry blossom particle, rose-pink monochrome wash, feather linework 0.3px, soft-focus vignette, Naoko Takeuchi aesthetic',
    recommendedEngine: 'seedance2',
    popularity: 65,
  },
  {
    id: 'sports-anime-kinetic',
    name: '热血竞技',
    nameEn: 'Sports Anime Kinetic',
    category: 'anime',
    thumbnail: '/styles/sports-anime-kinetic.svg',
    promptFragment: 'sports anime impact frame, radial speed streak, chromatic aberration on exertion peak, sweat freeze-frame, arena overhead wide shot, crowd motion blur, Haikyuu kinetic style',
    recommendedEngine: 'kling3',
    popularity: 72,
  },
  {
    id: 'retro-super-robot',
    name: '复古机甲',
    nameEn: 'Retro Super Robot',
    category: 'anime',
    thumbnail: '/styles/retro-super-robot.svg',
    promptFragment: '1970s super robot limited animation, flat cel primary palette, heavy black outline 4px, chrome cockpit lens flare, Mazinger Z design language, hand-painted cel background texture',
    recommendedEngine: 'kling3',
    popularity: 45,
  },
  {
    id: 'gothic-lolita-dark',
    name: '哥特暗幻',
    nameEn: 'Gothic Lolita Dark Fantasy',
    category: 'anime',
    thumbnail: '/styles/gothic-lolita-dark.svg',
    promptFragment: 'gothic lolita Victorian interior, Prussian blue deep shadow, ornate lace filigree texture, candelabra specular highlight, rose window bokeh disc, Rozen Maiden doll aesthetic',
    recommendedEngine: 'seedance2',
    popularity: 55,
  },
  {
    id: 'manga-bw-screentone',
    name: '黑白漫格',
    nameEn: 'B&W Manga Screentone',
    category: 'anime',
    thumbnail: '/styles/manga-bw-screentone.svg',
    promptFragment: 'B&W manga print screentone dot pattern, Zip-A-Tone gradient, parallel hatching shadow, speed-line panel burst, high-contrast inking, Berserk brushwork roughness',
    recommendedEngine: 'seedance2',
    popularity: 68,
  },
  {
    id: 'magical-girl-burst',
    name: '魔法变身',
    nameEn: 'Magical Girl Transform',
    category: 'anime',
    thumbnail: '/styles/magical-girl-burst.svg',
    promptFragment: 'magical girl transformation sequence, prism rainbow ribbon trail, starlight particle burst, pastel halo gradient, heart-shaped lens flare, Precure sparkle density, saturation 130%',
    recommendedEngine: 'kling3',
    popularity: 78,
  },
  {
    id: 'seinen-dark-realism',
    name: '青年硬漫',
    nameEn: 'Seinen Dark Realism',
    category: 'anime',
    thumbnail: '/styles/seinen-dark-realism.svg',
    promptFragment: 'seinen dark realism, rough crosshatch chiaroscuro, muted ochre charcoal palette, anatomically detailed musculature, Vagabond brushstroke inking, graphic novel close crop',
    recommendedEngine: 'seedance2',
    popularity: 58,
  },
  {
    id: 'toei-classic-70s',
    name: '东映经典',
    nameEn: 'Toei Classic 70s',
    category: 'anime',
    thumbnail: '/styles/toei-classic-70s.svg',
    promptFragment: 'classic Toei Animation cel paint, primary hue saturation +40, hard black outline 3px, hand-painted background matte, energy aura glow overlay, 4:3 aspect ratio nostalgia',
    recommendedEngine: 'kling3',
    popularity: 42,
  },
  {
    id: 'light-novel-isekai',
    name: '异世界封绘',
    nameEn: 'Light Novel Isekai Cover',
    category: 'anime',
    thumbnail: '/styles/light-novel-isekai.svg',
    promptFragment: 'light novel cover illustration, anime moe eye rendering, radial gradient fantasy sky, iris lens glare, layered outfit fabric detail, isekai castle backdrop, soft vignette halo',
    recommendedEngine: 'seedance2',
    popularity: 83,
  },
  {
    id: 'shinkai-godray',
    name: '新海诚霞光',
    nameEn: 'Shinkai Golden Hour',
    category: 'anime',
    thumbnail: '/styles/shinkai-godray.svg',
    promptFragment: 'Makoto Shinkai environment art, volumetric god-ray through cloud gap, cumulus cloud hyper-detail, golden-hour 3200K warm tone, lens dirt flare, atmospheric perspective haze',
    recommendedEngine: 'seedance2',
    popularity: 80,
  },
  {
    id: 'cel-3d-anime',
    name: '三维描线',
    nameEn: '3D Cel-Shaded Anime',
    category: 'anime',
    thumbnail: '/styles/cel-3d-anime.svg',
    promptFragment: 'toon-shaded 3D anime render, flat diffuse ramp shader, hand-drawn outline composite, subsurface hair clump scatter, PBR material on accessories, Unreal Engine anime shader',
    recommendedEngine: 'kling3',
    popularity: 73,
  },
  {
    id: 'xianxia-donghua',
    name: '仙侠国漫',
    nameEn: 'Xianxia Chinese Fantasy',
    category: 'anime',
    thumbnail: '/styles/xianxia-donghua.svg',
    promptFragment: 'Chinese xianxia cultivation aesthetic, hanfu silk cloth simulation, jade-green celestial particle, ink-wash mountain haze, spirit aura glow, dragon cloud swirl, MDZS visual style',
    recommendedEngine: 'kling3',
    popularity: 92,
  },
  {
    id: 'chibi-pastel',
    name: 'Q版萌化',
    nameEn: 'Chibi Pastel Super-Deformed',
    category: 'anime',
    thumbnail: '/styles/chibi-pastel.svg',
    promptFragment: 'super-deformed 1:2 head-body ratio, pastel watercolor background, exaggerated teardrop eye highlight, blush-circle cheek, squash-and-stretch bounce, kawaii soft drop shadow',
    recommendedEngine: 'viduq3',
    popularity: 76,
  },
  {
    id: 'retro-space-opera',
    name: '复古太空歌剧',
    nameEn: 'Retro Space Opera Anime',
    category: 'anime',
    thumbnail: '/styles/retro-space-opera.svg',
    promptFragment: '1970s space opera painted cel, starfield nebula background matte, vintage spacesuit design, Leiji Matsumoto melancholy silhouette, film grain halation, wide-eye figure against cosmos',
    recommendedEngine: 'seedance2',
    popularity: 38,
  },
  {
    id: 'neo-noir-rain',
    name: '霓虹侦探',
    nameEn: 'Neo-Noir Detective Rain',
    category: 'anime',
    thumbnail: '/styles/neo-noir-rain.svg',
    promptFragment: 'neo-noir anime urban rain, neon sign wet pavement reflection, trench coat silhouette, charcoal monochrome palette, single cyan neon accent, Darker than Black atmosphere, rain streak motion',
    recommendedEngine: 'seedance2',
    popularity: 62,
  },
  {
    id: 'trigger-explosive',
    name: '天元爆发',
    nameEn: 'Trigger Studio Explosive',
    category: 'anime',
    thumbnail: '/styles/trigger-explosive.svg',
    promptFragment: 'Trigger studio hyperkinetic animation, extreme foreshortening perspective, neon spiral energy burst, Gurren Lagann drill motif, bold flat color punch, sakuga animator smear frame',
    recommendedEngine: 'kling3',
    popularity: 67,
  },

  // ---------- ARTISTIC (+15) ----------
  {
    id: 'risograph',
    name: '丝网双色印',
    nameEn: 'Risograph Duotone',
    category: 'artistic',
    thumbnail: '/styles/risograph.svg',
    promptFragment: 'risograph duotone print, slight color misregistration, coarse halftone grain, fluorescent ink overlay, flat two-color palette, zine aesthetic, matte newsprint texture',
    recommendedEngine: 'seedance2',
    popularity: 73,
  },
  {
    id: 'paper-cut',
    name: '剪纸',
    nameEn: 'Paper Cut Art',
    category: 'artistic',
    thumbnail: '/styles/paper-cut.svg',
    promptFragment: 'layered paper cut silhouette, negative space design, handcrafted torn edge texture, flat cast shadow depth, Chinese folk art influence, two-tone or monochrome palette, crisp geometric forms',
    recommendedEngine: 'seedance2',
    popularity: 65,
  },
  {
    id: 'graffiti-street',
    name: '街头涂鸦',
    nameEn: 'Graffiti Mural',
    category: 'artistic',
    thumbnail: '/styles/graffiti-street.svg',
    promptFragment: 'spray paint graffiti mural, wild-style lettering influence, drips and overspray texture, urban concrete wall, saturated vibrant colors, bold outline strokes, throw-up shadow fills',
    recommendedEngine: 'kling3',
    popularity: 64,
  },
  {
    id: 'linocut-print',
    name: '版画木刻',
    nameEn: 'Linocut Print',
    category: 'artistic',
    thumbnail: '/styles/linocut-print.svg',
    promptFragment: 'linocut woodblock print, bold black outlines, hand-carved gouge marks, limited flat color palette, rough ink press texture, reduction print graphic shadows, high contrast silhouette',
    recommendedEngine: 'seedance2',
    popularity: 62,
  },
  {
    id: 'psychedelic-poster',
    name: '迷幻海报',
    nameEn: 'Psychedelic Poster',
    category: 'artistic',
    thumbnail: '/styles/psychedelic-poster.svg',
    promptFragment: '1960s psychedelic concert poster, swirling organic lettering, acid color palette, optical illusion patterns, Wes Wilson influence, fluorescent hues on deep background, kaleidoscope symmetry',
    recommendedEngine: 'kling3',
    popularity: 61,
  },
  {
    id: 'colored-pencil',
    name: '彩铅插画',
    nameEn: 'Colored Pencil Illustration',
    category: 'artistic',
    thumbnail: '/styles/colored-pencil.svg',
    promptFragment: 'colored pencil illustration, visible cross-hatching and layered wax buildup, slight paper grain texture, soft blended tones, editorial warm highlights, gentle color saturation, fine line details',
    recommendedEngine: 'seedance2',
    popularity: 60,
  },
  {
    id: 'bauhaus',
    name: '包豪斯',
    nameEn: 'Bauhaus',
    category: 'artistic',
    thumbnail: '/styles/bauhaus.svg',
    promptFragment: 'Bauhaus design language, primary color geometry, Kandinsky-Klee flat composition, circle-triangle-square motifs, functional formalism, grid-based layout, bold sans-serif type integration',
    recommendedEngine: 'seedance2',
    popularity: 59,
  },
  {
    id: 'expressionism',
    name: '表现主义',
    nameEn: 'Expressionism',
    category: 'artistic',
    thumbnail: '/styles/expressionism.svg',
    promptFragment: 'German Expressionism oil, distorted anxious perspective, raw heavy brushwork, emotional high-chroma palette, angular Kirchner-era forms, woodcut texture influence, psychological tension in composition',
    recommendedEngine: 'kling3',
    popularity: 58,
  },
  {
    id: 'impasto-acrylic',
    name: '厚涂丙烯',
    nameEn: 'Impasto Acrylic',
    category: 'artistic',
    thumbnail: '/styles/impasto-acrylic.svg',
    promptFragment: 'heavy impasto acrylic on canvas, raised palette knife ridges, tactile paint texture, bold color mixing in situ, gestural bristle drag marks, richly textured surface, sculptural paint depth',
    recommendedEngine: 'kling3',
    popularity: 57,
  },
  {
    id: 'charcoal-drawing',
    name: '炭笔素描',
    nameEn: 'Charcoal Drawing',
    category: 'artistic',
    thumbnail: '/styles/charcoal-drawing.svg',
    promptFragment: 'vine charcoal on newsprint, smudged tonal transitions, rough paper grain, high contrast black and white, gestural erasure highlights, compressed charcoal deep blacks, atmospheric sfumato blending',
    recommendedEngine: 'seedance2',
    popularity: 56,
  },
  {
    id: 'gongbi-finepainting',
    name: '工笔重彩',
    nameEn: 'Gongbi Fine Painting',
    category: 'artistic',
    thumbnail: '/styles/gongbi-finepainting.svg',
    promptFragment: 'gongbi fine line painting on silk, iron-wire brushwork outline, layered mineral pigment fills, meticulous feather and petal detail, Tang-Song dynasty color palette, flat spatial composition, gold leaf accent',
    recommendedEngine: 'seedance2',
    popularity: 55,
  },
  {
    id: 'oil-pastel',
    name: '油画棒',
    nameEn: 'Oil Pastel',
    category: 'artistic',
    thumbnail: '/styles/oil-pastel.svg',
    promptFragment: 'oil pastel on textured board, thick waxy strokes, saturated color blocks with imprecise outlines, heavily blended midtones, warm grainy surface, bold directness, visible pigment grain',
    recommendedEngine: 'seedance2',
    popularity: 53,
  },
  {
    id: 'abstract-expressionism',
    name: '抽象表现',
    nameEn: 'Abstract Expressionism',
    category: 'artistic',
    thumbnail: '/styles/abstract-expressionism.svg',
    promptFragment: 'abstract expressionist action painting, gestural drip and pour marks, large color field, de Kooning brushwork energy, raw canvas weave visible, spontaneous mark-making, emotional chromatic tension',
    recommendedEngine: 'kling3',
    popularity: 52,
  },
  {
    id: 'pointillism',
    name: '点彩派',
    nameEn: 'Pointillism',
    category: 'artistic',
    thumbnail: '/styles/pointillism.svg',
    promptFragment: 'pointillist stippling, pure unmixed color dots, optical color mixing at distance, Seurat systematic dot application, vibrant chromatic contrast, post-impressionist palette, uniform brush mark rhythm',
    recommendedEngine: 'seedance2',
    popularity: 48,
  },
  {
    id: 'etching-intaglio',
    name: '铜版蚀刻',
    nameEn: 'Etching & Intaglio',
    category: 'artistic',
    thumbnail: '/styles/etching-intaglio.svg',
    promptFragment: 'copper plate etching, fine crosshatch line engraving, acid-bitten rough texture, warm sepia-toned laid paper, intaglio ink depth, Rembrandt-era tonal gradation, precise drypoint burr marks',
    recommendedEngine: 'seedance2',
    popularity: 44,
  },

  // ---------- RETRO (+18) ----------
  {
    id: 'technicolor50s',
    name: '好莱坞彩色',
    nameEn: 'Hollywood Technicolor',
    category: 'retro',
    thumbnail: '/styles/technicolor50s.svg',
    promptFragment: 'Technicolor 3-strip dye transfer, oversaturated primaries, MGM studio backdrop, soft halation on highlights, 1950s glamour cinematography, 50mm medium-format lens',
    recommendedEngine: 'seedance2',
    popularity: 65,
  },
  {
    id: 'french-new-wave',
    name: '法式新浪潮',
    nameEn: 'French New Wave',
    category: 'retro',
    thumbnail: '/styles/french-new-wave.svg',
    promptFragment: 'hand-held 16mm Bolex, jump-cut rhythm, natural window light, orthochromatic black-and-white, flat Parisian mise-en-scene, nouvelle vague 1960, deep-focus street frame',
    recommendedEngine: 'kling3',
    popularity: 72,
  },
  {
    id: 'giallo',
    name: '杰洛惊悚',
    nameEn: 'Italian Giallo',
    category: 'retro',
    thumbnail: '/styles/giallo.svg',
    promptFragment: 'deep crimson backlighting, baroque chiaroscuro, extreme Dutch angle, Fuji 35mm pushed 1 stop, Italian genre cinema 1972, gloved-hand POV, mirror-reflection mise-en-scene',
    recommendedEngine: 'kling3',
    popularity: 58,
  },
  {
    id: 'kodachrome',
    name: '柯达暖调',
    nameEn: 'Kodachrome Slide',
    category: 'retro',
    thumbnail: '/styles/kodachrome.svg',
    promptFragment: 'Kodachrome 64 slide film, punchy yellow-greens, warm saturated reds, magenta shadow cast, ultra-fine grain, 1975 color temperature, transparency midtone pop',
    recommendedEngine: 'seedance2',
    popularity: 78,
  },
  {
    id: 'super8-home',
    name: '超八家庭',
    nameEn: 'Super 8 Home Movie',
    category: 'retro',
    thumbnail: '/styles/super8-home.svg',
    promptFragment: 'Kodak Super 8 Ektachrome, washed-out warm color shift, light leaks at frame edge, jittery handheld framing, 1970s family vacation texture, underexposed pastel midtones',
    recommendedEngine: 'kling3',
    popularity: 70,
  },
  {
    id: 'daguerreotype',
    name: '银版摄影',
    nameEn: 'Daguerreotype',
    category: 'retro',
    thumbnail: '/styles/daguerreotype.svg',
    promptFragment: 'daguerreotype silver-mercury plate, sepia metallic sheen, Victorian oval mat vignette, long-exposure motion blur, pin-sharp center detail, formal 1860s studio portrait pose',
    recommendedEngine: 'seedance2',
    popularity: 48,
  },
  {
    id: 'silent-film',
    name: '默片时代',
    nameEn: 'Silent Film Era',
    category: 'retro',
    thumbnail: '/styles/silent-film.svg',
    promptFragment: 'orthochromatic black-and-white, heavy corner vignette, iris aperture wipe reveal, hand-tinted sepia amber, intertitle card frame, 1920s theatrical projection artifact',
    recommendedEngine: 'seedance2',
    popularity: 55,
  },
  {
    id: 'soviet-constructivism',
    name: '苏式构成',
    nameEn: 'Soviet Constructivism',
    category: 'retro',
    thumbnail: '/styles/soviet-constructivism.svg',
    promptFragment: 'bold constructivist diagonal geometry, flat red and cream duotone, Rodchenko photomontage, high-contrast lithographic printing, 1924 Soviet avant-garde, geometric sans-serif overlay',
    recommendedEngine: 'seedance2',
    popularity: 52,
  },
  {
    id: 'pulp-cover',
    name: '纸浆封面',
    nameEn: 'Pulp Magazine Cover',
    category: 'retro',
    thumbnail: '/styles/pulp-cover.svg',
    promptFragment: '1940s gouache illustration, vivid complementary color palette, dramatic shadow rendering, halftone dot grain texture, pulp paper yellowing, Detective Fiction Weekly composition',
    recommendedEngine: 'seedance2',
    popularity: 63,
  },
  {
    id: 'bubble-era-japan',
    name: '泡沫日本',
    nameEn: 'Japan Bubble Era',
    category: 'retro',
    thumbnail: '/styles/bubble-era-japan.svg',
    promptFragment: 'late-1980s Tokyo bubble economy, warm neon sign bokeh, Fujifilm 400H color shift, shoulder-pad fashion detail, soft street-level bloom, Shinjuku night overexposed highlights',
    recommendedEngine: 'kling3',
    popularity: 82,
  },
  {
    id: 'wartime-newsreel',
    name: '战时新闻',
    nameEn: 'WWII Newsreel',
    category: 'retro',
    thumbnail: '/styles/wartime-newsreel.svg',
    promptFragment: '16mm wartime newsreel grain, orthochromatic desaturation, WWII documentary high-contrast shadow, March of Time composition framing, newsreel stamp overlay, 1943 print damage',
    recommendedEngine: 'kling3',
    popularity: 50,
  },
  {
    id: 'crt-broadcast',
    name: '阴极射线',
    nameEn: 'CRT Broadcast',
    category: 'retro',
    thumbnail: '/styles/crt-broadcast.svg',
    promptFragment: 'CRT phosphor scan-line texture, NTSC color bleed, RGB fringe chroma artifact, interlace flicker, rounded-corner vignette, 1950s broadcast studio palette, warm cathode-tube glow',
    recommendedEngine: 'seedance2',
    popularity: 75,
  },
  {
    id: 'spaghetti-western',
    name: '意式西部',
    nameEn: 'Spaghetti Western',
    category: 'retro',
    thumbnail: '/styles/spaghetti-western.svg',
    promptFragment: 'Sergio Leone extreme close-up, anamorphic 2.39:1 letterbox, amber Almeria desert haze, sun-bleached washed palette, 35mm Italian western grain, wide-to-tight stare-down framing',
    recommendedEngine: 'kling3',
    popularity: 67,
  },
  {
    id: '90s-disposable',
    name: '胶片傻瓜',
    nameEn: '90s Disposable Camera',
    category: 'retro',
    thumbnail: '/styles/90s-disposable.svg',
    promptFragment: 'disposable camera direct flash, red-eye artifact, slight fisheye barrel distortion, Kodak Gold 200 color cast, flat snapshot exposure, 35mm amateur scan grain, 1990s party casual framing',
    recommendedEngine: 'kling3',
    popularity: 85,
  },
  {
    id: 'meiji-tinted',
    name: '明治手彩',
    nameEn: 'Meiji Hand-Tinted Photo',
    category: 'retro',
    thumbnail: '/styles/meiji-tinted.svg',
    promptFragment: 'hand-tinted albumen silver print, watercolor overlay on sepia base, formal Meiji-era kimono pose, late 19th century Japanese photo studio, oval mat board, delicate pastel tint',
    recommendedEngine: 'seedance2',
    popularity: 45,
  },
  {
    id: 'grindhouse',
    name: '地下放映',
    nameEn: 'Grindhouse Exploitation',
    category: 'retro',
    thumbnail: '/styles/grindhouse.svg',
    promptFragment: '16mm drive-in print scratch, cigarette burn reel-change cue, color bleed desaturation, exploitation cinema vignette, 1970s grindhouse theatre damage, splatter-era chroma aberration',
    recommendedEngine: 'kling3',
    popularity: 62,
  },
  {
    id: 'euro-art-cinema',
    name: '欧陆艺术',
    nameEn: 'European Art Cinema',
    category: 'retro',
    thumbnail: '/styles/euro-art-cinema.svg',
    promptFragment: 'Ingmar Bergman flat Nordic diffused light, 1960s Eastmancolor grading, psychological tight close-up, winter grey palette, fine-grain 35mm Arriflex, expressionist shadow geometry',
    recommendedEngine: 'seedance2',
    popularity: 68,
  },
  {
    id: 'neon-showa',
    name: '昭和霓虹',
    nameEn: 'Showa Neon Japan',
    category: 'retro',
    thumbnail: '/styles/neon-showa.svg',
    promptFragment: '1960s Showa Japan hand-painted neon sign, tungsten-warm alley glow, Fuji Velvia warm shift, rain-wet cobblestone reflection, mid-century Tokyo street, dense kanji signage bokeh',
    recommendedEngine: 'kling3',
    popularity: 80,
  },

  // ---------- EXPERIMENTAL (+19) ----------
  {
    id: 'glitch-rgb',
    name: '故障RGB',
    nameEn: 'RGB Glitch Split',
    category: 'experimental',
    thumbnail: '/styles/glitch-rgb.svg',
    promptFragment: 'RGB channel split +8px horizontal offset, chromatic aberration fringe, VHS tracking error, scanline interlace flicker, digital noise grain 12%, corrupted JPEG block artifact',
    recommendedEngine: 'kling3',
    popularity: 78,
  },
  {
    id: 'light-painting',
    name: '光绘魔法',
    nameEn: 'Light Painting',
    category: 'experimental',
    thumbnail: '/styles/light-painting.svg',
    promptFragment: 'long-exposure light painting 30-second shutter, fiber-optic wand streak trails, steel wool spark shower, bokeh orb background, pitch-black environment, luminous color ribbon arcs',
    recommendedEngine: 'kling3',
    popularity: 65,
  },
  {
    id: 'liquid-metal',
    name: '液态金属',
    nameEn: 'Liquid Metal',
    category: 'experimental',
    thumbnail: '/styles/liquid-metal.svg',
    promptFragment: 'liquid mercury morphing surface, polished chrome wet reflection, iridescent oil-slick sheen, caustic light caustics floor, fluid simulation high-viscosity, cool silver tone gradient',
    recommendedEngine: 'kling3',
    popularity: 68,
  },
  {
    id: 'thermal-vision',
    name: '热成像',
    nameEn: 'Thermal Infrared',
    category: 'experimental',
    thumbnail: '/styles/thermal-vision.svg',
    promptFragment: 'FLIR thermal camera false-color, infrared palette black-purple-red-yellow-white gradient, heat bloom around warm bodies, temperature-mapped silhouette, sensor noise grain, clinical flatness',
    recommendedEngine: 'seedance2',
    popularity: 55,
  },
  {
    id: 'data-rain',
    name: '数字雨幕',
    nameEn: 'Digital Rain',
    category: 'experimental',
    thumbnail: '/styles/data-rain.svg',
    promptFragment: 'Matrix-style digital rain, falling green katakana monospace columns, CRT phosphor afterglow, pitch-black background, cascading binary streams, bright green glyph leading edge',
    recommendedEngine: 'kling3',
    popularity: 75,
  },
  {
    id: 'material-swap',
    name: '材质错置',
    nameEn: 'Material Displacement',
    category: 'experimental',
    thumbnail: '/styles/material-swap.svg',
    promptFragment: 'photo-realistic surface material displacement, porcelain cracked glaze on human skin, liquid-glass fabric drape, granite stone cloth impossible texture, hyperrealistic substitution render, studio light',
    recommendedEngine: 'seedance2',
    popularity: 58,
  },
  {
    id: 'sand-art',
    name: '沙画光台',
    nameEn: 'Sand Art Table',
    category: 'experimental',
    thumbnail: '/styles/sand-art.svg',
    promptFragment: 'backlit sand art table, amber granular texture, negative-space line art raked in sand, warm under-glow diffused light, kinetic sand flow, fine-grain earthy ochre and sienna tones',
    recommendedEngine: 'kling3',
    popularity: 45,
  },
  {
    id: 'double-exposure',
    name: '双重曝光',
    nameEn: 'Double Exposure',
    category: 'experimental',
    thumbnail: '/styles/double-exposure.svg',
    promptFragment: '35mm film double exposure blend, portrait silhouette filled with pine forest, screen blend mode, halftone grain 400 ISO, ghost landscape overlay, analog film base warm tone',
    recommendedEngine: 'seedance2',
    popularity: 85,
  },
  {
    id: 'neon-xray',
    name: '霓虹X光',
    nameEn: 'Neon X-Ray',
    category: 'experimental',
    thumbnail: '/styles/neon-xray.svg',
    promptFragment: 'medical X-ray radiograph aesthetic, skeletal bone structure visible, neon magenta-cyan colorize overlay, fluorescent edge glow on anatomy, dark void background, clinical flat lighting',
    recommendedEngine: 'seedance2',
    popularity: 60,
  },
  {
    id: 'pixel-melt',
    name: '像素熔化',
    nameEn: 'Pixel Melt',
    category: 'experimental',
    thumbnail: '/styles/pixel-melt.svg',
    promptFragment: 'pixelated image downward dissolution, 16-bit mosaic columns sliding gravity, game sprite decay, pixel tile flow cascade, dithered color bands, resolution degradation waterfall',
    recommendedEngine: 'kling3',
    popularity: 70,
  },
  {
    id: 'soundwave-viz',
    name: '声波涌动',
    nameEn: 'Soundwave Visualization',
    category: 'experimental',
    thumbnail: '/styles/soundwave-viz.svg',
    promptFragment: 'oscilloscope green phosphor waveform CRT, audio frequency spectrum equalizer bars, Lissajous figure overlay, monochrome sine wave data art, analog tube glow, vector scope pattern',
    recommendedEngine: 'kling3',
    popularity: 52,
  },
  {
    id: 'origami-light',
    name: '折纸光影',
    nameEn: 'Origami Hard Light',
    category: 'experimental',
    thumbnail: '/styles/origami-light.svg',
    promptFragment: 'crisp origami paper folding, sharp geometric crease lines, single hard directional key light, deep angular cast shadows, matte white 100gsm paper texture, low-polygon faceted origami crane',
    recommendedEngine: 'seedance2',
    popularity: 48,
  },
  {
    id: 'bioluminescence',
    name: '深海荧光',
    nameEn: 'Deep Sea Bioluminescence',
    category: 'experimental',
    thumbnail: '/styles/bioluminescence.svg',
    promptFragment: 'deep-sea bioluminescent organisms, electric blue dinoflagellate sparkle, pitch-black ocean void, luminous jellyfish tentacle tendrils, cyan-teal-violet bio-light, marine phosphorescence pulse',
    recommendedEngine: 'kling3',
    popularity: 72,
  },
  {
    id: 'deconstructed',
    name: '解构碎面',
    nameEn: 'Deconstructed Cubism',
    category: 'experimental',
    thumbnail: '/styles/deconstructed.svg',
    promptFragment: 'Cubist face fragmentation, portrait shards reassembled at conflicting angles, collage cut-paper geometry, wide negative space, planar multi-viewpoint faces, angular offset portrait planes',
    recommendedEngine: 'seedance2',
    popularity: 42,
  },
  {
    id: 'star-trails',
    name: '星轨时间',
    nameEn: 'Star Trail Long Exposure',
    category: 'experimental',
    thumbnail: '/styles/star-trails.svg',
    promptFragment: '8-hour star trail composite, concentric circular light arc rotation, Polaris fixed center, cold blue-white stellar streaks, dark mountain silhouette foreground, Milky Way core ambient glow',
    recommendedEngine: 'kling3',
    popularity: 67,
  },
  {
    id: 'micro-world',
    name: '显微世界',
    nameEn: 'Electron Microscope',
    category: 'experimental',
    thumbnail: '/styles/micro-world.svg',
    promptFragment: 'scanning electron microscope SEM aesthetic, 1000x magnification extreme macro, false-color scientific imaging, nanoscale surface topology, extreme shallow depth of field, monochrome with color-map overlay',
    recommendedEngine: 'seedance2',
    popularity: 50,
  },
  {
    id: 'holo-glitch',
    name: '全息故障',
    nameEn: 'Holographic Glitch',
    category: 'experimental',
    thumbnail: '/styles/holo-glitch.svg',
    promptFragment: 'holographic foil rainbow diffraction grating, prismatic spectral interference bands, iridescent chrome hologram surface, scanline disruption artifact, spectral color wash shimmer, metallic light play shift',
    recommendedEngine: 'kling3',
    popularity: 80,
  },
  {
    id: 'ink-diffusion',
    name: '墨迹扩散',
    nameEn: 'Ink Diffusion Bloom',
    category: 'experimental',
    thumbnail: '/styles/ink-diffusion.svg',
    promptFragment: 'ink drop macro in still water, marbling fluid dynamics bloom, suminagashi Japanese paper marbling, dye diffusion tendril spread, high-contrast dark plume, ebru swirl pattern, translucent ink cloud',
    recommendedEngine: 'kling3',
    popularity: 73,
  },
  {
    id: 'quantum-superpose',
    name: '量子叠影',
    nameEn: 'Quantum Superposition',
    category: 'experimental',
    thumbnail: '/styles/quantum-superpose.svg',
    promptFragment: 'triple-exposure ghost figure overlay, 3-layer translucent 40%-opacity figure blend, probability cloud haze, wave interference fringe pattern, motion blur stack superposition, ethereal multiplied silhouette',
    recommendedEngine: 'seedance2',
    popularity: 38,
  },

];

// 静态校验（v12.273：64 → 155 扩容后同步基线）。开发期断言，打包后 tree-shake。
// 断言的意义已从「凑够固定条数」转为「防止误删/误增与分类漂移」——改动本库时同步这里的数字。
if (process.env.NODE_ENV !== 'production') {
  const total = STYLE_PRESETS.length;
  if (total !== 155) {
    console.warn(`[style-presets] expected 155 styles, got ${total}`);
  }
  const byCategory = STYLE_PRESETS.reduce<Record<string, number>>((acc, s) => {
    acc[s.category] = (acc[s.category] ?? 0) + 1;
    return acc;
  }, {});
  const expectedByCategory: Record<string, number> = { realistic: 31, anime: 36, artistic: 27, retro: 30, experimental: 31 };
  for (const cat of ['realistic', 'anime', 'artistic', 'retro', 'experimental'] as const) {
    if (byCategory[cat] !== expectedByCategory[cat]) {
      console.warn(`[style-presets] category "${cat}" should have ${expectedByCategory[cat]} styles, got ${byCategory[cat] ?? 0}`);
    }
  }
  // id 去重检查
  const ids = new Set<string>();
  for (const s of STYLE_PRESETS) {
    if (ids.has(s.id)) console.warn(`[style-presets] duplicate id: ${s.id}`);
    ids.add(s.id);
  }
}

// ============ 便捷查询函数 ============

export function getStyleById(id: string): StylePreset | undefined {
  return STYLE_PRESETS.find(s => s.id === id);
}

export function getStylesByCategory(category: StylePreset['category']): StylePreset[] {
  return STYLE_PRESETS.filter(s => s.category === category);
}

/** 按流行度降序返回，可选 limit */
export function getPopularStyles(limit?: number): StylePreset[] {
  const sorted = [...STYLE_PRESETS].sort((a, b) => b.popularity - a.popularity);
  return limit ? sorted.slice(0, limit) : sorted;
}

/** 拼接风格 prompt 片段到用户 prompt 尾部 */
export function applyStyleToPrompt(basePrompt: string, styleId?: string): string {
  if (!styleId) return basePrompt;
  const style = getStyleById(styleId);
  if (!style) return basePrompt;
  return `${basePrompt}, ${style.promptFragment}`;
}

/** 获取风格的负面 prompt（如果有） */
export function getStyleNegativePrompt(styleId?: string): string | undefined {
  if (!styleId) return undefined;
  return getStyleById(styleId)?.negativePrompt;
}

/** 获取风格推荐的视频引擎（如果有） */
export function getStyleRecommendedEngine(styleId?: string) {
  if (!styleId) return undefined;
  return getStyleById(styleId)?.recommendedEngine;
}

// ============ v6.3 风格画廊 ============

/** 分类有序列表 + 中文标签 (画廊 tab 用). */
export const STYLE_CATEGORIES: { id: StylePreset['category']; label: string }[] = [
  { id: 'realistic', label: '写实' },
  { id: 'anime', label: '动漫' },
  { id: 'artistic', label: '艺术' },
  { id: 'retro', label: '复古' },
  { id: 'experimental', label: '实验' },
];

/** 分类中文标签 (兜底原值). */
export function categoryLabel(category: string): string {
  return STYLE_CATEGORIES.find((c) => c.id === category)?.label ?? category;
}

/** 风格搜索: 名 / 英文名 / 分类 / promptFragment 关键词 (大小写不敏感). 空 query 返全部. */
export function searchStyles(query: string, presets: StylePreset[] = STYLE_PRESETS): StylePreset[] {
  const q = (query || '').trim().toLowerCase();
  if (!q) return presets;
  return presets.filter((p) =>
    p.name.toLowerCase().includes(q) ||
    p.nameEn.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q) ||
    categoryLabel(p.category).includes(q) ||
    (p.promptFragment || '').toLowerCase().includes(q),
  );
}
