/**
 * /template/[token] · v2.19 P0.3 — server wrapper + OG metadata.
 *
 * This is a server component. It only:
 *   1. Resolves the token and reads the template on the server (lib/template-share → DB, no HTTP)
 *   2. Builds og:title / og:description / og:image / twitter:card meta
 *   3. Passes the token to the client component for the interactive UI
 *
 * The OG image itself is generated by opengraph-image.tsx in this folder (ImageResponse).
 *
 * Note: the server read does NOT call incrementViewCount — view counts only increment on the
 * client fetch to /api/templates/shared/[token], so OG preview crawlers do not inflate them.
 */

import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import SharedTemplateClient from './template-client';
import { getTemplateAssetForToken } from '@/lib/template-share';
import { getTranslations, normalizeLocale } from '@/lib/i18n';

export const dynamic = 'force-dynamic';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>;
}): Promise<Metadata> {
  const { token } = await params;
  const found = await getTemplateAssetForToken(token);
  const jar = await cookies();
  const locale = normalizeLocale(jar.get('qfmj-locale')?.value);
  const tRaw = getTranslations(locale);
  const t = tRaw as typeof tRaw & { publicUi: Record<string, string> };
  const ui = t.publicUi;

  if (!found) {
    return {
      title: ui.shareLinkUnavailableTitle,
      description: ui.shareLinkExpired,
      robots: { index: false, follow: false },
    };
  }

  const meta = (found.asset.metadata || {}) as {
    icon?: string;
    nameEn?: string;
    tags?: string[];
    description?: string;
  };
  const icon = meta.icon || '📄';
  const rawName = found.asset.name || ui.untitledTemplate;
  const name = locale === 'en' ? (meta.nameEn || rawName) : rawName;
  const description = (found.asset.description || meta.description || '').slice(0, 160);
  const tagsSummary = meta.tags && meta.tags.length > 0
    ? ui.tagsPrefix.replace('{n}', meta.tags.slice(0, 4).join(' · '))
    : '';

  const ogTitle = ui.ogTemplateTitle.replace('{icon}', icon).replace('{name}', name);
  const ogDescription = description
    || ui.ogTemplateDesc.replace('{n}', tagsSummary).trim();

  return {
    title: ogTitle,
    description: ogDescription,
    openGraph: {
      title: ogTitle,
      description: ogDescription,
      type: 'article',
      // opengraph-image.tsx injects og:image automatically — do not set the url by hand
    },
    twitter: {
      card: 'summary_large_image',
      title: ogTitle,
      description: ogDescription,
    },
    robots: { index: true, follow: true },
  };
}

export default async function SharedTemplatePage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  return <SharedTemplateClient token={token} />;
}
